# Elasticsearch Configuration
# M365 RAG System

cluster.name: m365-rag-cluster
node.name: es-node-1

# Network
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory
bootstrap.memory_lock: true

# Discovery
discovery.type: single-node

# Security
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false  # Enable with proper certificates in production
xpack.security.transport.ssl.enabled: false

# Machine Learning
xpack.ml.enabled: true

# Index defaults
action.auto_create_index: true

# CORS (if needed for direct access)
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-credentials: true

