version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: m365-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.ml.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-YourStrongPassword123!}
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:${ELASTIC_PASSWORD:-YourStrongPassword123!} http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: m365-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-YourStrongPassword123!}
      - xpack.security.enabled=false
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  tika:
    image: apache/tika:latest-full
    container_name: m365-tika
    ports:
      - "9998:9998"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9998/tika || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  elastic_data:
    driver: local

networks:
  elastic:
    driver: bridge
