services:
  - type: web
    name: typingmind-mcp-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_TOKEN
        value: p1Lhz4LCAH_uooyVkeLDH
      - key: PORT
        value: 10000
